# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

gems: [jekyll-paginate]
paginate: 5

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : OSiRIS
tagline: Open Storage Research InfraStructure
author :
  name : OSiRIS Project
  #email : blah@email.test
  github : https://github.com/MI-OSiRIS
  #twitter : username
  #feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://www.osris.org

#
# GitHub Project Pages (http://username.github.io/project-name)
#
#   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
#
# CAUTION:
#   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
#   - Only the following values are falsy: ["", null, false]
#   - When setting BASE_PATH it must be a valid url.
#     This means always setting the protocol (http|https) or prefixing with "/"
BASE_PATH : ""

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml

